allowBuilds:
  '@sentry/cli': true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@paalstack/react-ui@1.2.2'
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
